Adding user-friendly error message to prod environments
broadinstitute/single_cell_portal_core pull request #1078
Opened 2021-06-17 19:03 UTC by devonbush

This updates the ErrorBoundary code to display a user-friendly error message in production, but a full stack trace in all other environments. 
PRODUCTION VIEW:
![image](https://user-images.githubusercontent.com/2800795/122457304-80479000-cf7c-11eb-9939-393031ffb8b2.png)

OTHER ENVIRONMENTS:
![image](https://user-images.githubusercontent.com/2800795/122457352-8c335200-cf7c-11eb-93e8-e6e510a4cc63.png)

 `process.env.VIEW_ENV` is introduced as the variable that tracks the environment, this allows it to be easily changed during development workflow.  To see the production view,  just change line 4 of development.js to `process.env.VIEW_ENV = 'production'`, and restart the webpack server.  
 The alternative, using NODE_ENV or RAILS_ENV, means that in order to test the behavior under the production environment,  a production build would occur, which disables the live reload server and causes other complexities.  

This change therefore partially addresses SCP-2237, but I will hold off on updating the other environment references in JS until this is confirmed to work in actual production.

TO TEST:
 1. update a component that's within an error boundary to have an obvious JS error in its main render path.  (e.g. change line 45 of ScatterPlot.js to be `const [isLoading, setIsLoading] = foobar(false)`
 2. Load the explore tab for a study
 3. confirm an error message appears with full stack trace
 4. edit `config/webpack/development.js:4` to be `process.env.VIEW_ENV = 'production'`
 5. restart your webpack dev server and reload the page
 6. confirm the user-friendly error message appears with the support email

2021-06-17 19:12 UTC, ehanna4 commented
Is "Staging" intended to be most like "Prod" or "local/dev" ? If the former would it make sense to have the error messaging appear the same in "Staging" and "Prod"?

2021-06-21 13:55 UTC, devonbush commented
> Is "Staging" intended to be most like "Prod" or "local/dev" ? If the former would it make sense to have the error messaging appear the same in "Staging" and "Prod"?

Good question -- I put the full error trace in for easier debugging of staging errors, but I think you're right that it should be prod-like.  I'll switch the logic so the full trace only appears in dev

2021-06-21 14:04 UTC, eweitz requested changes
Good stuff!  I tested this locally and confirm it works.

I like the use of Node environment, but [other scenarios](https://github.com/broadinstitute/single_cell_portal_core/pull/450#discussion_r392524219) seem like a better use case.  Its use here slightly decreases observability, and I don't think the benefit of removing technical details from the error UI offsets that cost.  Details below!

2021-06-21 14:07 UTC, bistline approved these changes
Very helpful enhancement, but I agree with Eric's sentiment that this would also be useful in `production` as well for QA/UL purposes.  I'm approving proactively with the request that we apply this to all environments.

2021-06-22 01:59 UTC, devonbush commented
Yup, that's a good point.  I was less thinking of UX, but just the general security principle of 'never expose stack traces to users'.  But since this is all client-side, I don't think the security principle applies

2021-06-22 02:00 UTC, devonbush commented
Updated: 
![image](https://user-images.githubusercontent.com/2800795/122850930-0f85d800-d2dc-11eb-8755-7144d5466be8.png)

2021-06-22 15:28 UTC, eweitz approved these changes

2021-06-22 19:03 UTC, ehanna4 commented on app/javascript/components/visualization/ScatterPlot.js
> +  const [isLoading, setIsLoading] = duseState(false)
typo?

2021-06-22 19:21 UTC, devonbush commented on app/javascript/components/visualization/ScatterPlot.js
> +  const [isLoading, setIsLoading] = duseState(false)
ah, yup, leftover from when I was deliberately generating errors.  thanks!

2021-06-23 01:13 UTC, devonbush commented
test failures are caused by upstream TDR change -- unrelated to this work

2021-06-23 01:13 UTC, merged