Sort the annotations AlphaNumerically
broadinstitute/single_cell_portal_core pull request #1102
Opened 2021-07-19 20:13 UTC by ehanna4

Sort the annotations for scatterplot Alphanumerically.

Remove "legendrank" as that was not actually setting the order in the legend, it is coming from the annotation groups order.
Sorting the groups even with the million cell study added only about 3 ms so it seemed reasonable to continue with this approach.

Before:
<img width="475" alt="Screen Shot 2021-07-19 at 4 10 11 PM" src="https://user-images.githubusercontent.com/54322292/126221167-432e9b3c-d400-4ed3-aa9e-dd5ffd492045.png">
After:
<img width="666" alt="Screen Shot 2021-07-19 at 4 07 03 PM" src="https://user-images.githubusercontent.com/54322292/126221186-050d7c03-082f-4c12-85d3-6aaacc9d2456.png">

Another example of how the annotation groups will be sorted now:
<img width="188" alt="Screen Shot 2021-07-19 at 3 11 55 PM" src="https://user-images.githubusercontent.com/54322292/126221217-f0bab68c-c757-4de2-a7c1-356a8beb8569.png">

2021-07-19 20:30 UTC, jlchang reviewed
One major motivation was that Studies with numbers-as-labels (the default for Seurat clustering output) would sort numerically despite looking like a number.

Could you include in the PR description what the label sort order would look like for a study that had Seurat Cluster labels 1 through 12?

If you need a "real data" example, you could use the data in SCP1238 - just keep the study private as the content is unpublished data shared by our U19 collaborators.

2021-07-19 20:34 UTC, ehanna4 commented
> One major motivation was that Studies with numbers-as-labels (the default for Seurat clustering output) would sort numerically despite looking like a number.
> 
> Could you include in the PR description what the label sort order would look like for a study that had Seurat Cluster labels 1 through 12?
> 
> If you need a "real data" example, you could use the data in SCP1238 - just keep the study private as the content is unpublished data shared by our U19 collaborators.

Will do! Thanks for providing an example to use

2021-07-19 20:55 UTC, eweitz approved these changes
Looks good!  Thanks for the timing data.  I suggested a small maintainability improvement.

2021-07-19 20:55 UTC, eweitz commented on app/javascript/components/visualization/ScatterPlot.js
> +function sortAlphaNumerically(a, b) {
"[Natural sort](https://en.wikipedia.org/wiki/Natural_sort_order)" is the conventional term for this kind of sort, so preferring that name would help maintainability.

```suggestion
/** Give natural sort order for alphanumeric strings */
function sortNaturally(a, b) {
```

2021-07-19 20:55 UTC, eweitz commented on app/javascript/components/visualization/ScatterPlot.js
> +    plotlyTraces[0].transforms[0].groups.sort(sortAlphaNumerically)
```suggestion
    plotlyTraces[0].transforms[0].groups.sort(sortNaturally)
```

2021-07-20 14:17 UTC, bistline requested changes
I'm not sure what is causing this, but it appears that we are losing the assignments and the plots aren't showing the correct populations.  I've tried with both strings and numbers as "group" type labels.  Oddly, the colors are correct in terms of the labels, but the points are not.  I tried blowing away the cache, but the problem is persisting.

I've included screenshots from SCP1 (sNuc-seq) and SCP383 (10X 1.3M cell) both locally and on production, for comparison:

localhost, strings
![localhost_strings](https://user-images.githubusercontent.com/729968/126339286-96ce5b7a-80b0-4a02-8942-08b91b36c460.png)

production, strings
![production_strings](https://user-images.githubusercontent.com/729968/126339322-b5e931e5-b5c1-404f-9e3f-26f6b679b341.png)

localhost, numbers
![localhost_numbers](https://user-images.githubusercontent.com/729968/126339334-a5e2b7f0-67a9-4c8a-9733-809b5b509fdd.png)

production, numbers
![production_numbers](https://user-images.githubusercontent.com/729968/126339349-3fba47c0-3495-49e6-be38-dac5879f0e52.png)

2021-08-02 14:07 UTC, ehanna4 commented
Closing this PR - hoping to utilize the library Jon pointed out as a better way to do legends and with the hope that it supports longer term goals of better customizing plotly things.

2021-08-02 14:07 UTC, closed without merging