Adding data-analytics-name prop to track raw counts exemption requests
broadinstitute/single_cell_portal_core pull request #1152
Opened 2021-09-10 16:28 UTC by bistline

This update adds the `data-analytics-name` property to the link for requesting a raw counts exemption request.  This is required for automatically tracking exemption requests in Mixpanel.  While not an exact proxy, it will at least allow some automated tracking.  It is possible this will over-count, whereas tracking Zendesk tickets will be an exact count.

MANUAL TESTING
* Boot portal as normal and sign in
* Ensure the `raw_counts_required_frontend` feature flag is turned on for your account
* Create a new study, or load the upload wizard for one w/o any raw counts expression matrices
* Open the Chrome dev tools > Network panel
* Click the "Request Exemption" link in the "Processed Matrix" tab
* Note the POST to Bard, with the event of `click:link`, and the text property of `raw-counts-exemption`.

This PR supports SCP-3632.

2021-09-10 16:34 UTC, eweitz approved these changes

2021-09-13 20:46 UTC, devonbush requested changes
In the unlikely event of zendesk getting hacked, we should add `rel="noopener noreferrer"` to the link

See https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

2021-09-14 13:49 UTC, bistline commented
> In the unlikely event of zendesk getting hacked, we should add `rel="noopener noreferrer"` to the link. (and I recognize that it wasn't there before)
> 
> See https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

Sure thing - we should probably do that everywhere we say `target: :_blank` in our markup.

2021-09-14 14:33 UTC, devonbush approved these changes
Nice, good call on handling that link update in a bunch of places

2021-09-14 15:16 UTC, merged