Db upload raw counts
broadinstitute/single_cell_portal_core pull request #1181
Opened 2021-09-28 10:43 UTC by devonbush

2021-09-28 16:00 UTC, eweitz requested changes
Good stuff!  I noted many nits, but overall it's exciting to see this moving along quickly.

I found one blocker, which seems trivial to fix -- see comments beginning "Blocker:".

The PR title and description need content (including Jira ticket in title for auditability).

2021-09-28 16:11 UTC, bistline requested changes
I am unable to get the form overlay that prevents uploading processed matrices before raw counts to render.  Several of the constants in `ProcessedExpressionStep.js` are coming back `undefined`, and the state is not being set correctly.  I do have both raw counts feature flags turned on for my testing account, so I'm not sure what the issue is.

Modulo that, and Eric's comments, the rest looks good to me.

2021-09-28 16:39 UTC, eweitz approved these changes

2021-09-28 19:26 UTC, devonbush commented
> Good stuff! I noted many nits, but overall it's exciting to see this moving along quickly.
> 
> I found one blocker, which seems trivial to fix -- see comments beginning "Blocker:".
> 
> The PR title and description need content (including Jira ticket in title for auditability).

Yes, thanks for the fast reviews -- I created this PR, and then got pulled into a bunch of meetings before I could add content -- should have opened in draft first :)

2021-09-29 10:02 UTC, eweitz commented on app/javascript/components/upload/ExpressionFileForm.js
> +              &nbsp;Expression Matrix
Sweet!  Also, which of those 3 strings is logged?

2021-09-29 15:53 UTC, bistline approved these changes

2021-09-29 16:39 UTC, merged