Validate cell names are unique for Metadata and Cluster files (SCP-3767)
broadinstitute/single_cell_portal_core pull request #1271
Opened 2021-11-22 18:54 UTC by ehanna4

This adds client-side validation to check that the cell names in a Metadata or Cluster file are all unique. If there is a duplicated cell name it is displayed to the user with a request to fix the duplicates.

To test:
- pull this branch
- go to the upload wizard in a study you can add files to
- try to upload the file that is included in this PR: `test/js/lib/validate-file-content.test.js`
- you should see an error message indicating the duplicate cell names

Error message is added to the list of errors if a file has multiple things wrong:
![Screen Shot 2021-11-22 at 12 00 43 PM](https://user-images.githubusercontent.com/54322292/142918807-92e4e0ba-d992-4053-b7f6-8a140664418f.png)

Error message is shown for a file with duplicated cell names
![Screen Shot 2021-11-22 at 11 58 27 AM](https://user-images.githubusercontent.com/54322292/142918909-ede5b666-204a-408d-bc6a-3b4196f18a81.png)

2021-11-22 20:29 UTC, eweitz requested changes
Kudos on getting this working in an unfamiliar area of the codebase!  Jumping into new patterns is _hard_.

I might be missing something, but it seems this implementation unnecessarily skips reusing existing constructs like `readLinesAndType` and `sniffDelimiter`, and then re-implements them (with some unaccounted edge cases) as part of a function in `io.js`.  

That causes this validation to have rather different inner workings from existing validations, which in turn requires unduly repetitive and hard-to-maintain additions to many validation tests.

The top of `parseFile` has a line:

```
const { lines, mimeType } = await readLinesAndType(file, 2)
```

I can't suggest this inline due to GitHub PR UI limitations, but the changes I suggest below would need `parseFile` updated to something roughly like:

```
const { lines, mimeType } = await readLinesAndType(file)
const headerLines = lines.slice(0, 2)
```

Then in `parseLines` replace all uses of `lines` with `headerLines`, _except_ in the call to `validateUniqueCellNamesWithinFile`.  

Benefits:
* Eliminate the many calls to `mockCatchDuplicateCellNames` in unrelated tests
* Simplify the logic of this new rule by eliminating unnecessary use of `await`, promises, `Error` and related `try` / `catch`.
* Simplify parameters by eliminating unnecessary new `file` parameter in several functions
* Simplify architecture for client-side file validation, by reusing existing constructs

I think the essence of your validation is sound.  I hope these details help integrate it smoothly into the existing patterns!

2021-11-22 22:15 UTC, bistline commented
Functionality works as advertised, but I agree with Eric about reusing the existing infrastructure.  I'm holding off on approving/requesting changes until that is dealt with.  But so far it works!

2021-11-24 15:04 UTC, eweitz approved these changes
Much cleaner!  I suggest an optimization and maintainability refinement. 

Now that `tables` is potentially many, many lines instead of just 2, performance is more important than elegance.  Traditional `for` loops are [much faster](https://leanylabs.com/blog/js-forEach-map-reduce-vs-for-for_of/#arraymap-vs-for-vs-forof) than modern `map` iteration, thus my suggestion below.

2021-11-24 15:04 UTC, eweitz commented on app/javascript/lib/validation/validate-file-content.js
> +      issues = await validateCapFormat(headerTable, fileType, file)
This function doesn't have a third parameter.

```suggestion
      issues = await validateCapFormat(headerTable, fileType)
```

2021-11-24 18:30 UTC, bistline approved these changes

2021-11-29 19:22 UTC, devonbush approved these changes
nice!  This will be a big win for our users -- just one suggestion on inlining the test content for easier reviewability

2021-11-29 19:22 UTC, devonbush commented on test/js/lib/validate-file-content.test.js
> +    const { errors, summary } = await validateFileContent({ name: 'cluster_duplicate_cell_names.txt' }, 'Cluster')
I'd like to minimize the amount of test data files we have to maintain, as it's tricky to keep track of which files are used where, and makes reviewing test cases difficult.  So I would shorten the file down to 4-5 rows, and then inline the content similar to how we inlined the content in the `catches text file with .gz suffix` 
(And I know this is different than the other cluster files in this test, but I think Eric merged those while I was on vacation :) )

2021-12-02 16:08 UTC, ehanna4 commented
Build Failure due to ongoing known issue with secrets and Travis

2021-12-02 16:08 UTC, merged