Updating bulk download labels & HCA filtering (SCP-3982)
broadinstitute/single_cell_portal_core pull request #1328
Opened 2022-01-24 02:39 UTC by devonbush

SCP-3982.  The functional change is to only show finalized loom files as 'analysis' files in the UX.  Note that we still pass along every file we find to the UI components in case we want to later refine the UI with message like "[X] contributor generated files may be available here". But the non-finalized loom analysis files are now classified as "contributor_analysis_files and hidden in the UI. 

The info popups have also been improved -- the SCP types link to the appropriate zendesk documentation, and the HCA analysis popup links to the HCA info page. 

![image](https://user-images.githubusercontent.com/2800795/150713113-d9a3176e-3ab4-420a-a47e-1cec598a3e41.png)

TO TEST:
1. sign in and have XDSS enabled
2. do a search that yields both HCA and SCP studies (`cow lung`) worked in my environment
3. Confirm the SCP file column info popups link appropriately
4. Confirm the HCA 'analysis' column info popup links appropriately
5. Confirm zero or one file shows up in the analysis column for each HCA study

2022-01-24 14:33 UTC, eweitz requested changes
Code looks mostly good!

Only blocker: a true-positive Azul-related [build failure](https://github.com/broadinstitute/single_cell_portal_core/runs/4916488842?check_suite_focus=true#step:4:4207).  It seems a test assertion needs to be updated.

```
  1) Failure:
AzulSearchServiceTest#test_should_get_summary_file_information_from_project_shortnames [/home/app/webapp/test/integration/lib/azul_search_service_test.rb:159]:
--- expected
+++ actual
@@ -1 +1 @@
-["source", "count", "upload_file_size", "file_format", "accession", "project_id", "file_type"]
+["source", "count", "upload_file_size", "file_format", "accession", "project_id", "is_intermediate", "file_type"]


418 runs, 1720 assertions, 1 failures, 0 errors, 1 skips
```

Beyond that, I suggest a few copyediting refinements, and ask about `noreferrer`.

2022-01-24 14:33 UTC, eweitz commented on app/javascript/components/search/controls/download/DownloadSelectionTable.js
> +      <a href="https://singlecell.zendesk.com/hc/en-us/articles/360060610292-Matrix-Files" target="_blank" rel="nofollow noreferrer">
Out of curiosity, why `noreferrer`?  Insofar as referrer is ever valuable, I can see it being valuable here.

2022-01-24 14:33 UTC, eweitz commented on app/javascript/components/search/controls/download/DownloadSelectionTable.js
> +       This does not include contributor generated files or intermediate files, which can be downloaded directly from HCA
Full stop polish:

```suggestion
      Loom files of <a href="https://broadinstitute.github.io/warp/docs/Pipelines/Optimus_Pipeline/Loom_schema/" target="_blank" rel="nofollow noreferrer">finalized raw counts</a>.<br/>
       This does not include contributor generated files or intermediate files, which can be downloaded directly from HCA.
```

2022-01-24 14:33 UTC, eweitz commented on app/javascript/lib/InfoPopup.js
> +/**
```suggestion

/**
```

2022-01-24 15:05 UTC, bistline commented on app/javascript/components/search/controls/download/DownloadSelectionTable.js
> +      <a href="https://singlecell.zendesk.com/hc/en-us/articles/360060610292-Matrix-Files" target="_blank" rel="nofollow noreferrer">
This is a security enhancement to avoid [exploits](https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/) to `window.opener` in Javascript.

2022-01-24 15:07 UTC, devonbush commented on app/javascript/components/search/controls/download/DownloadSelectionTable.js
> +      <a href="https://singlecell.zendesk.com/hc/en-us/articles/360060610292-Matrix-Files" target="_blank" rel="nofollow noreferrer">
Thanks for calling this out.  `noreferrer` became best practice since older versions of firefox didn't support noopener. https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/.  (Incidentally, I just realized I'd put 'nofollow' instead of noopener by mistake).    I see your point about us wanting to preserve the referrer so Zendesk can see where it came from.  But I think the security need outweighs that -- since Zendesk is not inside our FISMA boundary, we need to treat it as a site which may become compromised.  

Reading a bit more, it looks like as of 2021, most major browsers do noopener by default, so this `rel` attribute which was best practice, may no longer be needed given enough time for everyone to update

2022-01-24 15:15 UTC, bistline requested changes
Looks good, except two small issues in `azul_search_service.rb`.  One is just a debug logging call, but the other looks like it will in fact cause a regression (double assignment of variable).

2022-01-24 15:15 UTC, bistline commented on app/lib/azul_search_service.rb
> +      puts file_summary
Debug call

2022-01-24 15:47 UTC, eweitz commented on app/javascript/components/search/controls/download/DownloadSelectionTable.js
> +      <a href="https://singlecell.zendesk.com/hc/en-us/articles/360060610292-Matrix-Files" target="_blank" rel="nofollow noreferrer">
Good point on using `noreferrer` for security likely being out-dated advice.  Some detail:

[Firefox has supported `rel="noopener"`](https://caniuse.com/rel-noopener) since FF 52 was released in early 2017.  Earlier versions were end-of-lifed long ago, and thus should likely be considered insecure and unsupported in SCP.  

So it seems that article's security argument has not been valid for almost 5 years, and we can securely pass referrer to sites outside our FISMA boundary.

2022-01-24 19:44 UTC, eweitz approved these changes

2022-01-24 19:44 UTC, eweitz commented on app/javascript/components/search/controls/download/DownloadSelectionTable.js
> +        Matrix file documentation
Like the others:

```suggestion
        Matrix file documentation.
```

2022-01-25 20:51 UTC, bistline approved these changes

2022-01-26 03:22 UTC, merged