Add metrics to capture the match type for SCP studies
broadinstitute/single_cell_portal_core pull request #1429
Opened 2022-03-22 19:35 UTC by ehanna4

For our OKR on adding author info to studies adding this metric will enable us to more easily see how many studies match the search based on term, phrase or author match. 

This PR will only add tracking for SCP studies (aka not Azul studies), since the OKR is around author search which isn't supported for Azul at this time.

There is definitely potential follow up work to add Azul match data and more study result info. However getting this bit out for OKR tracking seemed most important so I am planning to file a follow on ticket for that other work as long as there is no strong opposition.

To test:
- Pull this branch and run it locally
- Search from the home page using different terms and/or phrases
- Check out the network tab for events titles 'search' and check out the property scpStudiesMatchData
- Or check out mixpanel dev for the same

<img width="1488" alt="Screen Shot 2022-03-22 at 3 33 04 PM" src="https://user-images.githubusercontent.com/54322292/159561242-88d1f87e-821d-4d11-a548-6b23d811d96a.png">

2022-03-22 20:31 UTC, devonbush requested changes
Code looks good.  Please update 'should return search results using keywords' in search_controller_test.rb to test your new metrics object.

Also, it looks like if a combined keyword+facet search is done, this will return the # and types of keyword matches, regardless of whether they were filtered out by the facet results.  Is that intended? (this is probably a rare enough case that it doesn't really matter)

2022-03-23 14:10 UTC, eweitz requested changes
Good stuff!  I hope this is the first in a string of analytics enhancements for search.

I note one blocker: Mixpanel log properties should be flattened per SCP convention.  Even if nested properties are searchable (I suspect they aren't, or at least not nearly as easily), being consistent in format with other log properties is important for analyst UX.

Here's how nested properties look in Mixpanel -- not glanceable, and likely problematic for easy queryability:

<img width="1680" alt="Nested_property_in_Mixpanel__SCP_2022-03-23" src="https://user-images.githubusercontent.com/1334561/159718273-cc189305-5b15-400e-aa9e-18340e828fa0.png">


I also suggest several non-blocking refinements on log property nomenclature ("matches" -> "results") and segmentation (e.g. `"scpStudiesMatchData: {'numMatchesByAuthor': 2}"` -> `"numResults:scp:author": 2`).

2022-03-23 14:17 UTC, ehanna4 commented
> Also, it looks like if a combined keyword+facet search is done, this will return the # and types of keyword matches, regardless of whether they were filtered out by the facet results. Is that intended? (this is probably a rare enough case that it doesn't really matter)

Is a combined keyword+facet search the inferred search? If so this will set the `matchData` to an empty {} so it will report nothing rather than incorrect data

2022-03-23 19:00 UTC, devonbush commented
I should have been clearer -- by a combined keyword + facet search I meant if someone searches for the facet `Species: rattus norvegicus` and the text 'Smith', that will return no results to the user, since there are no studies that have both that facet and the text 'Smith'.  However, the text match "Smith" will find two studies.  I believe your change means that we will record the search as having two text matches, even though it returned none to the user.  I *think* that's desirable or at least "good enough for now", but just wanted to clarify

2022-03-24 13:15 UTC, eweitz approved these changes
Thanks for addressing that issue, and incorporating the suggestions!

2022-03-24 13:15 UTC, eweitz commented on app/controllers/api/v1/search_controller.rb
> +          puts('in keyword')
```suggestion
```

2022-03-24 13:48 UTC, ehanna4 commented
@devonbush  oh okay I think actually it will report nothing for match data if the facet filter is used, regardless if there's a match or not

only "pure" text searches have match data

<img width="1461" alt="Screen Shot 2022-03-24 at 9 44 36 AM" src="https://user-images.githubusercontent.com/54322292/159930121-390321ff-e397-4222-acd9-2b325da33ae7.png">
<img width="1477" alt="Screen Shot 2022-03-24 at 9 43 31 AM" src="https://user-images.githubusercontent.com/54322292/159930112-e554e510-f772-4c9e-8e48-0c687dd6a032.png">
<img width="1490" alt="Screen Shot 2022-03-24 at 9 44 07 AM" src="https://user-images.githubusercontent.com/54322292/159930117-6d3652e8-50c2-4548-9e44-07b4ed87d883.png">

2022-03-24 16:51 UTC, devonbush commented
thanks for clarifying!

2022-03-24 16:51 UTC, devonbush approved these changes

2022-03-24 17:45 UTC, merged