Fix global gene search for studies with default numeric annotation (SCP-4200)
broadinstitute/single_cell_portal_core pull request #1440
Opened 2022-03-31 20:37 UTC by eweitz

This fixes the display of results for global gene search when the study has a default annotation of type "numeric".

Previously, likely for at least 1-2 years, an error was displayed for such results.  Now, an annotated scatter plot is shown, similar to what's shown in gene search for the Explore tab in Study Overview (#1435).

Here's how it looks:

https://user-images.githubusercontent.com/1334561/161144590-a0d6c4f2-6c27-4f77-9566-69766fb9f524.mov

This satisfies SCP-4200.

2022-04-01 00:06 UTC, devonbush approved these changes
I'd lean toward sending the whole default annotation identifier just because it seems cleaner than extracting a single boolean, given that we'll probably want to know other things about the default annotation later.  But I don't have my heart set on it :)

2022-04-01 00:06 UTC, devonbush commented on app/javascript/components/search/genes/StudyGeneExpressions.jsx
Add a `getAnnotationFromIdentifier` helper method to cluster-utils.js that mirrors the existing `getIdentifierFromAnnotation`, and then you can do
```suggestion
const defaultAnnotation = getAnnotationFromIdentifier(study.default_annotation)
const defaultAnnotationIsNumeric = defaultAnnotation?.type === 'numeric'
```
For bonus points, update line 80 of ExploreTabRouter.jsx to use the new helper function

2022-04-07 17:46 UTC, eweitz commented
To give adequate review time, I'll keep this as originally scoped and open a separate PR when the other fix is ready.

2022-04-08 14:46 UTC, ehanna4 requested changes
I think this change might have broken a previous fix for another type of error.
When I run a gene search on `development` 2 studies do not display a graph but instead display a small message explaining why no graph is shown. However, when I run this branch now I see a 'Something went wrong.' red error message
Before (on development branch):
<img width="1229" alt="Screen Shot 2022-04-08 at 10 42 59 AM" src="https://user-images.githubusercontent.com/54322292/162462764-9bb06ea2-88a7-4542-bb4c-8cdcb315bfb7.png">
With this branch:
<img width="1229" alt="Screen Shot 2022-04-08 at 10 44 12 AM" src="https://user-images.githubusercontent.com/54322292/162462840-16b4442a-2a63-4e72-9d0e-b51da4cd3080.png">
<img width="723" alt="Screen Shot 2022-04-08 at 10 41 55 AM" src="https://user-images.githubusercontent.com/54322292/162462859-4d4ec523-052d-4082-bc70-474d5c724b3a.png">

2022-04-08 15:52 UTC, eweitz commented
Good catch, @ehanna4!  Fixed in 8eb26f2.  The fix now accounts for studies that lack visualizations.

2022-04-08 18:27 UTC, jlchang approved these changes
Functional review: 
- confirmed annotated scatter generated for studies with default annotation of TYPE numeric 
- confirmed no plot generated for studies with gene expression that have no cluster file and instead the appropriate message "This study does not have cluster data to support visualization in the portal" is conveyed.

2022-04-08 20:02 UTC, ehanna4 approved these changes
Nice, confirmed previous bug is gone and no new issues 👍

2022-04-11 13:16 UTC, merged