Updating to latest version of `singlecellportal/rails-baseimage` (SCP-4290)
broadinstitute/single_cell_portal_core pull request #1462
Opened 2022-04-20 17:44 UTC by bistline

This updates our Dockerfile to use the latest release of `singlecellportal/rails-baseimage:2.0.0`.  This changes the underlying `ubuntu` image from `18.04` to `20.04`, as well as updating to the latest release of the `phusion/passenger-docker` image.  In addition, this update changes our default Ruby version to `2.6.9`, and will allow us to update to `3.1.x` in the future if we so choose.

MANUAL TESTING
To ensure that this image builds correctly:
1. Pull this branch
2. Authenticate into vault, and ensure Docker is running on your machine
3. Run either one of the following commands in the project root directory:
```
### only build the Docker image
docker build -t single_cell_docker:latest -f Dockerfile .

### build the Docker image and boot the portal container (will take dramatically longer)
bin/load_env_secrets.sh -p secret/kdux/scp/development/$(whoami)/scp_config.json \
                        -r secret/kdux/scp/development/$(whoami)/read_only_service_account.json \
                        -s secret/kdux/scp/development/$(whoami)/scp_service_account.json
```

This PR satisfies SCP-4290

2022-04-20 17:45 UTC, eweitz approved these changes

2022-04-20 17:45 UTC, eweitz commented on README.md
> +![Build Status](https://github.com/broadinstitute/single_cell_portal_core/actions/workflows/run-all-tests.yml/badge.svg)
Nice!

2022-04-20 18:56 UTC, bistline commented
Build failure looks like something went completely sideways as opposed to a specific regression.  Testing locally to confirm.

2022-04-20 20:09 UTC, bistline commented
> Build failure looks like something went completely sideways as opposed to a specific regression. Testing locally to confirm.

Local testing didn't show anything, though I found a potential issue I'm patching.  Going to chalk this up to usual CI gremlins.

2022-04-20 21:30 UTC, bistline commented
Well, run went sideways again, but local dockerized test passed w/o issue:

```
Finished in 2583.470732s, 0.1695 runs/s, 0.7076 assertions/s.

438 runs, 1828 assertions, 0 failures, 0 errors, 2 skips

You have skipped tests. Run with --verbose for details.
Lcov style coverage report generated for Unit Tests to /home/app/webapp/coverage/lcov
Cleaning up...
...cleanup complete.
Total elapsed time: 53 minutes, 52 seconds

### All test suites PASSED ###
```

2022-04-21 01:42 UTC, devonbush commented
the code looks good to me, but given the extensive changes, we should only merge this without a green build as a last resort.  fortunately, we've got time

2022-04-21 01:43 UTC, devonbush requested changes
Looks good, just needs a green build

2022-04-21 16:17 UTC, devonbush approved these changes
Nice work!

2022-04-21 18:24 UTC, merged