fixing sorting bugs, adding :created_at and :view_count for HCA entries (SCP-4287)
broadinstitute/single_cell_portal_core pull request #1475
Opened 2022-04-28 20:22 UTC by bistline

This update fixes some lingering bugs with sorting results from cross-dataset search requests, where results are either instances of the `Study` class, or `Hash` entries representing HCA projects.  Now, any requested search & sort order will support a mix of both result classes.  In addition, HCA entries now include their original `submissionDate` as a proxy for `created_at`, and a default `view_count` of `0`, as we have no data on views from Azul.

MANUAL TESTING
1. Pull this branch and boot as normal
2. Open the Swagger API documentation, and go to the search endpoint
3. Run a search that will return a mix of SCP & HCA entries, such as:
    * facets: `species:NCBITaxon_9606`
    * terms: `HIV`
4. Note that results return in a specific order by looking at the `matching_accessions` attribute in the response
5. Change the `order` parameter to both `recent` and `popular`, and note that the request completes and changes the order accordingly

This PR satisfies SCP-4287.

2022-04-29 02:53 UTC, devonbush requested changes
This is some nice elegant code.  Please allow me to be a broken record and say that search code should have test cases :).   Since these sort params aren't supported in our UX, the test case doesn't need to be extensive, copying the beginning from  test 'should return search results using facets' ` from line 135 of search_controller_test.rb, adding a sort param, and then just confirming it doesn't break is probably sufficient

2022-04-29 02:53 UTC, devonbush commented on app/controllers/api/v1/search_controller.rb
> +      # extract study attribute (like accession) accounting for source (SCP vs. external)
this is nice

2022-04-29 15:53 UTC, eweitz approved these changes

2022-04-29 20:29 UTC, bistline commented
> This is some nice elegant code. Please allow me to be a broken record and say that search code should have test cases :). Since these sort params aren't supported in our UX, the test case doesn't need to be extensive, copying the beginning from test 'should return search results using facets' ` from line 135 of search_controller_test.rb, adding a sort param, and then just confirming it doesn't break is probably sufficient

@devonbush See [da3cba5](https://github.com/broadinstitute/single_cell_portal_core/pull/1475/commits/da3cba55d59816969bf44efc648959578894d619)

2022-05-02 15:03 UTC, ehanna4 approved these changes

2022-05-02 18:14 UTC, merged