persist hidden traces (SCP-4380)
broadinstitute/single_cell_portal_core pull request #1518
Opened 2022-06-06 14:44 UTC by devonbush

To support browsing spatial clusters while keeping certain cell types hidden, this persists the hidden legend entries, as well as the 'splitLabelArrays' param.  This puts the hidden traces in the URL.  This may cause issues for some extremely large number of hidden traces, but Chrome's URL limit is 2MB, so even hiding 10000 traces that are each 100 characters long should work.  

TO TEST:
 1. load a study that has two clusters with a common annotation (e.g. a study-wide annotation).  For example, the `chicken_raw_counts` synthetic study
 2. View a cluster, select the study-wide annotation, and then hide one or more traces
 3. Switch to the other cluster, confirm the traces remain hidden
 4. Switch to a different annotation, and then switch back, confirm traces are no longer hidden
 5. Load a study with pipe-delimited array labels (e.g. `array_mouse_eye` synthetic study). 
 6. Confirm that you can split/merge array labels

2022-06-06 17:41 UTC, bistline approved these changes

2022-06-07 20:27 UTC, eweitz requested changes
The persisting traces are a nice touch!  I verified they work locally.  But I found a related bug.

Blocker: the default view in the "Murine vision and HIV with arrays" lacks a label legend in my local test, but [equivalent study on staging](https://singlecell-staging.broadinstitute.org/single_cell/study/SCP298/murine-vision-and-hiv-with-arrays#study-visualize) has a legend.

<img width="1676" alt="Screen Shot 2022-06-07 at 4 23 12 PM" src="https://user-images.githubusercontent.com/1334561/172476109-b5b8a25a-39d5-4ad6-9dce-66b12c88ff6e.png">

2022-06-08 01:01 UTC, devonbush commented
Nice catch Eric--that bug happened if the default annotation for a study was cluster, and the user didn't change an annotation quickly (which I almost always did)

2022-06-08 12:50 UTC, devonbush commented
Build failure is Azul facet search - unrelated

2022-06-08 15:12 UTC, merged