Fix Image Pipeline integration
broadinstitute/single_cell_portal_core pull request #1683
Opened 2022-11-29 02:45 UTC by eweitz

This is a draft, not yet ready for review.

2022-12-05 19:32 UTC, bistline requested changes
Tiny blocker re: `getopts` formatting.  Otherwise this looks good.  It would be nice if we can figure out what causes the hotfix deploy to fail so we can test it better.

2022-12-05 21:44 UTC, bistline approved these changes

2022-12-05 21:45 UTC, eweitz commented on bin/boot_docker
> +while getopts "n:N:e:d:D:m:M:r:s:k:K:f:F:p:h:u:P:H:o:S:y:g:t:R:w:W:A:a" OPTION; do
Fixed in a3c1721, thanks for the catch.

2022-12-08 18:39 UTC, ehanna4 approved these changes
Code looks good, ran the tests from https://github.com/broadinstitute/single_cell_portal_core/pull/1687 and was successful which the description here says is sufficient. Also saw the deployment of this to Staging built and tests others had completed there are available.

2022-12-08 20:44 UTC, merged