Draft: Reducing false negatives for Codecov integration
broadinstitute/single_cell_portal_core pull request #1709
Opened 2023-01-18 20:54 UTC by bistline

#### BACKGROUND & CHANGES
This update alters metrics for Codecov in an effort to reduce false negatives on coverage calculations that fail PR checks.  The `patch` check has been disabled in favor of `project`, since global coverage is the published metric for this repository.  Additionally, an analysis of recently closed PRs with a failed Codecov check has shown that these failures were due to a drop in global coverage of ~0.05%.  The threshold for failing has now been increased to 0.1% to reduce these uninformative failed checks.

#### MANUAL TESTING
The checks section below should only display the `codecov/project` check, and it should pass since coverage is not affected by this update.

2023-01-19 15:29 UTC, eweitz requested changes
Nice signal-to-noise improvement!  Please update "false negative" to "false positive" in the title and description of this PR, though.

For some time, we've used "[false positive](https://github.com/broadinstitute/single_cell_portal_core/search?q=false+positive&type=issues)" to refer to tests that fail in the absence of a real bug.  This logic for software tests is borrowed from [medical tests](https://en.wikipedia.org/wiki/False_positives_and_false_negatives).  For example, if a medical test for a virus says you have the virus and you are not really infected, then that's a false positive.  Similarly, if a software test for a defect says you have a defect but it's not really a bug, then that's a false positive.

The principle here is that a "positive" result _reports_ a problem.  Whether there is _actually_ a problem is the "true" and "false" part.  Check out [others' thoughts on this](https://testfully.io/blog/false-positive-false-negative), if it's of interest.

Here's how the logic applies in the context of code coverage tests:

* True positive: Code coverage _did_ drop below threshold we care about, and was reported as such
* True negative: Code coverage _did not_ drop below threshold we care about, and was reported as such
* False positive: Code coverage _did not_ drop below threshold we do not care about, but was reported as dropping below it
* False negative: Code coverage _did_ drop below threshold we care about, but was reported as _not_ dropping below it

2023-01-19 15:34 UTC, bistline commented
Looks like I broke `codecov.yaml`:

```
Commit YAML is invalid
Coverage data is unable to be displayed, as the commit YAML appears to be invalid.
```

2023-01-19 16:12 UTC, eweitz approved these changes

2023-01-19 18:21 UTC, michelle-vel reviewed
Interesting change! I see that this will change the threshold for failures to make the failed checks more reliable

2023-01-23 16:59 UTC, ehanna4 approved these changes
Seems like a smart change, I have indeed almost always ignored the Patch percentage when it was so small, this seems like it will improve the cognitive load of opening and approving a PR

2023-01-23 17:05 UTC, merged