Enlarge plots by economizing study title placement (SCP-5186)
broadinstitute/single_cell_portal_core pull request #1860
Opened 2023-08-21 12:45 UTC by eweitz

_Draft: not yet ready for review_

This makes visualizations bigger by moving the study title into the navigation bar.

2023-08-29 19:58 UTC, eweitz commented
I've converted this back to a draft to account for the refactoring entailed by #1867, and a bug found by Jon.

2023-08-30 13:52 UTC, jlchang requested changes
Blocker (still reviewing, but thought I'd communicate this blocker early)

I don't think we have a synthetic study that has more than one "experiment" that would have surfaced the need for clustering information in violin plot titles:
> The violin plot title also oddly noted the clustering -- which is mainly relevant for scatter plots. The violin plots are much more about expression in a gene across groups in an annotation. 
The violin plot reflects the expression of a gene across groups in a annotation **relative to the selected clustering**. Therefore both clustering and annotation are relevant to the violin plot. An example would be SCP44 in production (We use this one for our manual smoke tests):
The default clustering "Atlas of epithelial cells" is derived from normal mice so the [violin plot for `Reg3b`](https://singlecell.broadinstitute.org/single_cell/study/SCP44/small-intestinal-epithelium?genes=Reg3b&cluster=Atlas%20of%20epithelial%20cells%20%28Figure%201%29&spatialGroups=--&annotation=Mouse--group--study&subsample=all&tab=distribution#study-visualize) doesn't show striking differences between the mice in the clustering. In contrast, a separate experiment in the study, visualized with the clustering "Infection with enteric pathogens", shows that mice infected with salmonella (and one H. polygyrus infected mouse) have increased expression of `Reg3b`, an anti-microbial gene. The clusterings have different mice - normal mice for the altas and infected + non-infected mice for the second experiment.

Two clusterings may share an annotation but the violin plot from that shared annotation will be different if the clusterings are derived from different cells. In studies set up with multiple experiments, the selected clustering provides important context for the annotation being visualized and should be included in the violin plot title.

2023-08-31 12:06 UTC, eweitz commented
> Two clusterings may share an annotation but the violin plot from that shared annotation will be different if the clusterings are derived from different cells. In studies set up with multiple experiments, the selected clustering provides important context for the annotation being visualized and should be included in the violin plot title.

Insightful catch!  I've updated as you suggest -- here's how it looks.

<img width="1512" alt="Violin_plot_title_refined__SCP_2023-08-31" src="https://github.com/broadinstitute/single_cell_portal_core/assets/1334561/3f297c11-d022-46cd-97c0-92df15ba703f">

2023-10-17 19:13 UTC, bistline approved these changes
Much nicer overall!  The usability gains are very nice, and we gain a lot of vertical real estate back.

2023-10-17 19:13 UTC, bistline commented on app/javascript/lib/layout-utils.js
> +export function adjustGlobalHeader() {
FWIW I checked on production, and the longest study title we have is `Intra-tumoral injection of caerin 1.1 and 1.9 peptides in vaccinated TC-1 tumour bearing mice with PD-1 blockade modulates macrophage heterogeneity and the activation of CD8+ T cells in the tumour microenvironment`.  I renamed one of my local studies to that and this dealt with that just fine.

2023-10-17 19:15 UTC, bistline commented
Test failures are due to Terra release happening at the same time...

2023-10-24 12:58 UTC, jlchang approved these changes
Functional review - works as expected. Looking forward to the additional real estate!

Two non-blocking suggestions -  

1. Would coloring the title text help to make the title easier to catch the eye? 

Looking at the title in the nav bar, because so much of our UI in Explore is white on dark blue AND because the Title text is pretty small (to accommodate long titles), it feels a little "lost in the crowd". I'm not suggesting a color (I have below-average color sense) but I'm including a screenshot to show how color might make the title easier to pick out for someone unfamiliar with our layout:

<img width="1042" alt="Screenshot 2023-10-24 at 8 43 32 AM" src="https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/b0c5862c-cf9f-4461-8cb2-bf92d4154f4a">


2. Should we make sure that the info icon for DE doesn't wrap to the next line?

<img width="1146" alt="Screenshot 2023-10-24 at 8 53 24 AM" src="https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/6d90901c-cf74-4289-81f6-0a841b9c47cd">

2023-11-17 15:24 UTC, eweitz commented
The most recent build failure seems like a false positive.  The exit code indicates an out-of-memory (OOM) error.

```
.search_controller_test.rb:179 test_should_return_search_results_using_numeric_facets starting
search_controller_test.rb:179 test_should_return_search_results_using_numeric_facets completed (9.341 sec)
.search_controller_test.rb:296 test_should_run_inferred_search_using_facets starting
Error: Process completed with exit code 137.
```

We have [1 prior recorded case of that](https://github.com/broadinstitute/single_cell_portal_core/pulls?q=is%3Apr+%22Error%3A+Process+completed+with+exit+code+137%22+is%3Aclosed+).  I'll re-run the build.

2023-11-17 20:18 UTC, merged

2023-11-17 20:22 UTC, eweitz commented
Thanks for the useful reviews.  I ended up increasing study header font size slightly, and fixing a few other issues.  I deferred refining the info icons as that's a pre-existing issue; these changes don't change its incidence.