File validation/update fixes for AnnData UX (SCP-5473)
broadinstitute/single_cell_portal_core pull request #1973
Opened 2024-01-23 22:44 UTC by bistline

#### BACKGROUND & CHANGES
This update addresses several form validation/state issues with the AnnData UX.  These issues include:

* Not being able to update the form after initially saving (unless the page is reloaded), due to a [file validation error](https://broad-institute.sentry.io/issues/4681656120/)
* Form components for "data fragments" (like clustering, expression) not enforcing required fields, leading to ingest errors like `ingest_pipeline.py ingest_cluster: error: the following arguments are required: --name`
* Server-side validation of AnnData form data fragments not enforcing presence of required values
* Accidental re-parsing of AnnData files using the `remote_location` feature when updating forms, leading to parse failures and deletion of data
* Accidental removal of AnnData files on parse failure when using `remote_location` feature (should persist in bucket)

Now, the required fields are enforced both client- and server-side.  This will prevent the above ingest error from occurring as the file cannot be saved in an invalid state.  Secondly, form data is correctly merged after the initial save to account for the `reference_anndata_file` value still being present in the form.  This allows updates to the form after the initial save, and no longer requires a page refresh to correctly set the state.  Additionally, updates to the forms that do not specify new data (like adding clustering entries) will not re-launch parse jobs if the AnnData file was specified with the `remote_location` feature.  Lastly, `AnnData` files specified with the `remote_location` will no longer be removed on parse failure.

Demo of form bug fixes:

https://github.com/broadinstitute/single_cell_portal_core/assets/729968/a8b6af39-eb62-40b8-8167-57d64c289e7d

#### MANUAL TESTING
1. Boot all services and sign in
2. Create a new study, and select the AnnData UX
3. Note the Save buttons being disabled with the proper error messages in the Expression & Clustering forms
4. Download a copy of `compliant_pbmc3K.h5ad` from [here](https://console.cloud.google.com/storage/browser/_details/broad-singlecellportal-staging-testing-data/anndata/compliant_pbmc3K.h5ad;tab=live_object?project=broad-singlecellportal-staging) if you don't have a valid AnnData file locally
5. Select a species in the Expression form, and specify `X_umap` for the `obsm_key_name` in the clustering form, but do not set any other values
6. Note the form validation still states that `library_preparation_protocol` is still required in the Expression form, and `name` is still required in the Cluster form
7. Upload the AnnData file (or place in bucket and use GS URL feature) and click save
8. Note the save fails with the correct error messages
9. Provide the missing data and retry the upload/save, noting that it succeeds

2024-01-24 15:13 UTC, eweitz approved these changes
Code and demo video look good!  I note a few non-blocking nits.

In 0:26-28 of the video, I was surprised to see a ~1 second delay in the "Save" button becoming enabled, after focus is blurred in the AnnData tab.  Naively, I'd expect the button to enable in < 0.1 s after blur.  My guess is it's doing server-side validation, which seems heavier-duty than required in that particular case.  But it's robust and reasonably fast, so probably not worth speeding up right now.

2024-01-24 18:04 UTC, bistline commented on app/models/ann_data_file_info.rb
> +                       "#{data_type} fragment missing #{key} in form #{extra_info}")
We don't log the server-side validation failures, no - traditionally we never have.  Mostly these are database-level restrictions (missing required fields/associations).  What actionable information would you envision us gleaning from these events?

2024-01-24 18:05 UTC, bistline commented
> Code and demo video look good! I note a few non-blocking nits.
> 
> In 0:26-28 of the video, I was surprised to see a ~1 second delay in the "Save" button becoming enabled, after focus is blurred in the AnnData tab. Naively, I'd expect the button to enable in < 0.1 s after blur. My guess is it's doing server-side validation, which seems heavier-duty than required in that particular case. But it's robust and reasonably fast, so probably not worth speeding up right now.

I think that lag is the client doing a GET on the file in the bucket to determine what to do.  Since it's `AnnData`, it's a bit of a no-op since we don't do any actual validation.  I can confirm if that in fact what the lag is.

2024-01-29 13:47 UTC, jlchang requested changes
Functional test, a few permutations on AnnData file validation did not behave as expected:
- If I supply `library_preparation_protocol` and omit `species`, I'm allowed to save the file and it succeeds on ingest. (Upload wizard confirms that no species was supplied)
- Error message meant to provide specificity when obsm_key_name is missing becomes cryptic when no cluster name is provided (perhaps fall back to "in clustering form" for error message?)
<img width="426" alt="Screenshot 2024-01-29 at 8 46 08 AM" src="https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/c1c88783-839a-48b2-8137-83db9ea8ea51">



- [optional] If I follow the manual testing instructions, BUT provide an invalid AnnData file, for a period of time, the file will be marked as `parsed` until the subsequent validation failure and then the file is deleted - perhaps we should delay setting `parsed` until the `ingestSummary` event has reported in? (will also mention this refinement request in the reference AnnData mixpanel logging PR)
- [FYI] If I follow the manual testing instructions, get the initial error, try to fix it but don't correct both missing attributes, it looks like some cruft from a prior upload attempt is not cleared so I get really odd error messages:
<img width="422" alt="Screenshot 2024-01-29 at 8 01 11 AM" src="https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/b08ae7ed-bad8-4f3c-830d-ffed61255085">
Note: I could not reproduce the exact behavior above but was able to generate something similar if I tried upload with an invalid gsURL, followed by upload in the same instance of the form with a valid gsURL. See https://github.com/broadinstitute/single_cell_portal_core/pull/1971#pullrequestreview-1848753916 (I don't know why linking to the specific comment won't behave :(

2024-01-29 14:41 UTC, bistline commented
> Functional test, a few permutations on AnnData file validation did not behave as expected:
> 
> * If I supply `library_preparation_protocol` and omit `species`, I'm allowed to save the file and it succeeds on ingest. (Upload wizard confirms that no species was supplied)
> * Error message meant to provide specificity when obsm_key_name is missing becomes cryptic when no cluster name is provided (perhaps fall back to "in clustering form" for error message?)
> 
> <img alt="Screenshot 2024-01-29 at 8 46 08 AM" width="426" src="https://private-user-images.githubusercontent.com/6005195/300482196-c1c88783-839a-48b2-8137-83db9ea8ea51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Mzk0MjEsIm5iZiI6MTcwNjUzOTEyMSwicGF0aCI6Ii82MDA1MTk1LzMwMDQ4MjE5Ni1jMWM4ODc4My04MzlhLTQ4YjItODEzNy04M2RiOWVhOGVhNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTQzODQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhmMDE3MDMxNDVjODgwMzI2ZTAwNjg0MGQ0ZTQ4MTU4ZWU5NjVhNWI3ZWU2NzljM2NmNjMyZDM4OWMxY2U2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I3xVp17f4BS8EG5mT0MgQ5RohBAOmK8m5UMtMWpg490">
> * [optional] If I follow the manual testing instructions, BUT provide an invalid AnnData file, for a period of time, the file will be marked as `parsed` until the subsequent validation failure and then the file is deleted - perhaps we should delay setting `parsed` until the `ingestSummary` event has reported in? (will also mention this refinement request in the reference AnnData mixpanel logging PR)
> * [FYI] If I follow the manual testing instructions, get the initial error, try to fix it but don't correct both missing attributes, it looks like some cruft from a prior upload attempt is not cleared so I get really odd error messages:
> 
> <img alt="Screenshot 2024-01-29 at 8 01 11 AM" width="422" src="https://private-user-images.githubusercontent.com/6005195/300479603-b08ae7ed-bad8-4f3c-830d-ffed61255085.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Mzk0MjEsIm5iZiI6MTcwNjUzOTEyMSwicGF0aCI6Ii82MDA1MTk1LzMwMDQ3OTYwMy1iMDhhZTdlZC1iYWQ4LTRmM2MtODMwZC1mZmVkNjEyNTUwODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMTQzODQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmM0ZDk4NzgxYWI3MTM0YWQ2ZjcyMzQwOWYwYmQwYzliNDAwMWU1MWI3MWVhOTQ1M2Q3YTIyZWExNWM2YzcyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IPJNLmBv5YtwGmDlQOjw6U-da6V-rFVuD2bn3OnIiVM"> Note: I could not reproduce the exact behavior above but was able to generate something similar if I tried upload with an invalid gsURL, followed by upload in the same instance of the form with a valid gsURL. See [PR1971](https://github.com/[/pull/1971](https://github.com/broadinstitute/single_cell_portal_core/pull/1971)#pullrequestreview-1848753916)

Good suggestions - regarding the `id not unique` errors: I had experienced this several times as well, and thought I had addressed it with the [latest commit](https://github.com/broadinstitute/single_cell_portal_core/pull/1973/commits/1bc70c366f43eb46001d6eb354a6a6f11d2a8b8b#diff-dd932ac1120ae518b6ad97a701ba5f11446255c72ebcca0748c78e1bc8a284afR103).  Can you confirm that you have the most up-to-date version of this branch locally?  If so then the fix didn't completely address it.

2024-01-29 15:04 UTC, jlchang commented
> Can you confirm that you have the most up-to-date version of this branch locally? If so then the fix didn't completely address it.

Git says my branch is up to date with 'origin/jb-anndata-form-validation'.
`commit 1bc70c366f43eb46001d6eb354a6a6f11d2a8b8b (HEAD -> jb-anndata-form-validation, origin/jb-anndata-form-validation)`

2024-01-29 21:38 UTC, jlchang requested changes
Most of the weird stuff is gone but If I try and upload while missing an attribute and then retry, I get "Remote location is already taken".
![Screenshot 2024-01-29 at 4 09 17 PM](https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/b3058567-cc68-42cf-ba6c-4459d1f3eb87)
For that particular gsURL, I can't perform upload but if i supply a different gsURL, I can upload. So `delete` isn't clearing out all info about the failed upload.

If I click delete on the AnnData tab, I'd hope I would get a fresh start but wanted an upload failure so I created a second, invalid clustering entry, THEN I fat fingered the URL (pasted the entire description into the gsURL box and got a well-deserved "remote location taken" error. Forgetting my premise that `delete` would be needed, I re-tried the correct URL and got more of those duplicate ID errors BUT only for that second, invalid clustering entry "bar", the original first clustering (aka. "foo") is gone:

![Screenshot 2024-01-29 at 4 15 12 PM](https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/ec8a3ecf-728e-4d83-9245-657f34f8696c)
FYI, clicking `delete` on the AnnData tab does not clear data in the Expression matrix tab.
Also, for that second, invalid clustering that became the sole clustering, clicking `delete` in the clustering tab didn't do anything. I had to reload the page and got sent to the AnnData experience page. `delete` for clustering entries generally get an eternal spinner if there is.

Follow up on clustering `delete`:
If I've tried and failed to upload a file and shift to the clustering tab before I click `delete` on the AnnData page, the `delete` button on the clustering tab is an X
![Screenshot 2024-01-29 at 4 30 26 PM](https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/3cd38a0e-7f87-4cb4-807c-91df93a5e5b4)
Clicking on the X does not clear the form:

![Screenshot 2024-01-29 at 4 30 36 PM](https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/e14e3747-91f6-4498-b5ff-d0480a6d2114)
But clicking `delete` on the AnnData tab will cause the clustering tab to empty...

Also, probably no way around it but, if I cut and pasted into the gsURL box, the `Save` button can't update until I click out of the box:
![Screenshot 2024-01-29 at 4 11 07 PM](https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/56b59d6f-c0ea-4ffb-a186-1dfa608fbc3c)

2024-01-29 21:59 UTC, bistline commented
Ok, I'll look into these.  My first attempt wasn't able to reproduce any of this, but I'll keep trying.

> Also, probably no way around it but, if I cut and pasted into the gsURL box, the Save button can't update until I click out of the box:

This is by design - we either listen for the `onChange` event (every keystroke), or `onBlur` (when the field loses focus by user clicking away).  The former means we're making API requests to Google (and logging to Mixpanel) on every keystroke, which seems unnecessary.  I opted for the latter as it seems more economical.  I do agree that it's a bit of a hindrance, but the request only asks for 100 bytes of the file and returns in ~100ms, so the delay is tiny.

2024-01-29 22:11 UTC, bistline commented
I see the issues with the forms - I'll try to figure out how to properly garbage collect after the delete as I think this is what's leading to the weird state.  I was also able to trigger the `remote location is already taken` error, and I think this is just a side effect of local development and the fact that we (usually) only have one job worker for DelayedJob.  Once the file is parsed, the `DeleteQueueJob` takes ~8-10s to complete:

```
I, [2024-01-29T17:00:55.038383 #1071]  INFO -- : 2024-01-29T17:00:55-0500: [Worker(host:wm306-020 pid:1071)] Job DeleteQueueJob#perform (id=65b81ff394ec8f026a310f02) (queue=default) COMPLETED after 8.1855
```

Also, there's the `SearchFacet.update_all_facet_filters` job that runs after every ingest/delete, which is a much longer running job.  I tried the upload/delete without refreshing the page second time, but I waited until the delete job was done before clicking `Save` a second time.  I didn't get an error, so I'm fairly certain this is just a timing issue that won't manifest on staging/production as there's 8 different job workers.

2024-01-30 14:12 UTC, jlchang commented
> Once the file is parsed, the `DeleteQueueJob` takes ~8-10s to complete:
Ah, good to know. I'll make sure I wait for the delete job next time.

2024-02-01 14:26 UTC, eweitz approved these changes

2024-02-02 22:58 UTC, jlchang approved these changes
Functional review:
Error messages display as intended
Manual tests work _as long as the `Save` button in the expression matrix tab is not used after fixing the missing library preparation protocol error_
Will add video of duplicated cluster fragment into follow on ticket SCP-5499

Thanks for tackling these thorny validations issues!

2024-02-05 14:50 UTC, merged