Enable URL parameters for numeric cell facets, restore for categorical
broadinstitute/single_cell_portal_core pull request #2009
Opened 2024-04-09 15:53 UTC by eweitz

This is a draft, please don't review yet.

https://github.com/broadinstitute/single_cell_portal_core/assets/1334561/2b5c2a0d-f272-4096-bbba-6bd1f9f17db2

2024-04-09 21:23 UTC, bistline approved these changes

2024-04-10 13:31 UTC, jlchang requested changes
Facet filtered URLs do not seem to restore state when the view is toggled out of the filter plotted cells panel (leaving the panel restores the view to all cells not filtered by the legend but the facet filtered URL remains) then returned to the filter plotted cells panel (The filter plotted cells panel reflects the facet filtered URL [epithelial deselected] but the plot shows the unfiltered state [epithelial plotted]).


https://github.com/broadinstitute/single_cell_portal_core/assets/6005195/a0490189-80d3-42e0-83bd-d8db033c3d7e

Note: early in the video there is a race condition glitch that resets a deselected filter - likely a non-issue on production where filter facet loading is much quicker.

We also have an issue with an [ambiguous UX ](https://github.com/broadinstitute/single_cell_portal_core/pull/2002#pullrequestreview-1972035242) with respect to `reset view` vs reloading the page from using the browser's `reload` functionality (please read linked comment). The toggle from filtered to unfiltered further complicates this ambiguous UX. With respect to this PR I propose that we revisit the decision to restore the "all cells not filtered by the legend" view. For the rest of the ambiguous UX, we could ticket future work to bring "restore default view" and "reset page for current view" functionality in physical proximity <- is there additional complexity vis-a-vis bookmarks?

Once the post-toggle inconsistency between URL state (with filter plotted cells panel open) and view is addressed, I'll be happy to do additional testing. I have not tested the different flavors of numeric filtering yet.

2024-04-10 14:00 UTC, eweitz commented
Thanks for reporting those issues, Jean!

> Facet filtered URLs do not seem to restore state when the view is toggled out of the filter plotted cells panel (leaving the panel restores the view to all cells not filtered by the legend but the facet filtered URL remains) then returned to the filter plotted cells panel (The filter plotted cells panel reflects the facet filtered URL [epithelial deselected] but the plot shows the unfiltered state [epithelial plotted]).

This is a separate, pre-existing issue.  Once SCP-5553 is fixed, this effect will be resolved.

> We also have an issue with an ambiguous UX with respect to reset view vs reloading the page from using the browser's reload functionality (please read linked comment). The toggle from filtered to unfiltered further complicates this ambiguous UX and I propose that, with the parametrized URLs, perhaps we no longer need/want to restore the "all cells not filtered by the legend" view?

I agree that's an issue, and read the linked comment.  But it is also beyond the scope of the ticket, which is enabling URL parameters for numeric cell facets, and restoring URL parameters for categorical cell facets (i.e., restoring categorical cell facet URL parameterization to the state it was in as of PR #1942).

If you'd like to iterate on "Reset view" vs. browser refresh, in the context of bookmarks, cell filtering, and beyond, then please create a follow-on ticket and I'd be happy to collaborate there.

2024-04-10 15:07 UTC, jlchang approved these changes
Thanks for pointing out that the toggle glitch issue is already ticketed.

I'll make a ticket for the other suggestion [SCP-5590](https://broadworkbench.atlassian.net/browse/SCP-5590)

2024-04-10 15:07 UTC, merged