Better handling of non-existent annotations (SCP-5867, SCP-5868)
broadinstitute/single_cell_portal_core pull request #2169
Opened 2024-11-12 19:22 UTC by bistline

#### BACKGROUND & CHANGES
Currently, if the specified annotation is not found in a visualization request, the API will fall back to the default (or first available) annotation for that study.  This has several unintended consequences, one of them being that normal penetration scans that look for security vulnerabilities can result in memory/CPU saturation for a deployed instance as multiple bogus requests result in loading default data.  Now, if an annotation is specified and not found, the API will correctly respond `404`.  Normal "empty" requests that do not specify an annotation will still load the default annotation for a study, if one is available.

Additionally, known malicious requests that can lead to potential caching issues are blocked at the routing level with `400`.  While not strictly necessary, this will further reduce load by exiting before checking the cache on requests that are part of a security scan.  Since these scans are ever-evolving, the `404` approach is the more complete solution.

#### MANUAL TESTING
1. Boot as normal and load any study with visualizations
2. Confirm the empty default view renders without issue
3. Open the Network tab in Chrome Dev Tools
4. Select a different annotation to populate parameters into the URL
5. In the URL, change the name of the annotation to `not-found`.  For example, if the `annotation` parameter is `cell_type__ontology_label--group--study`, change it to `not-found--group--study` and submit the request.
6. Confirm that you see the error message `Error: Annotation "not-found" could not be found` and that the associated request in the network tab has a status of `404`.
7. Select a different annotation and confirm the plot is restored
8. Repeat step 5, but use `UPDATEXML` as the annotation name
9. Confirm the plot shows an error with the message `Bad request` and the associated request in the network tab shows a status of `400`

2024-11-13 15:55 UTC, eweitz approved these changes
Code looks good!  This nicely refines #2168.  

For our future reference, more context is [in Slack](https://broadinstitute.slack.com/archives/CBEHTH601/p1731418200513639).

2024-11-13 15:55 UTC, eweitz commented on app/controllers/api/v1/visualization/annotations_controller.rb
> +          end
Kudos on the key insight to prevent server resource flooding by failing fast here, and equivalent areas.

2024-11-13 21:17 UTC, jlchang requested changes
Works as described and I think a small tweak might be useful.

If I test as described and use URL
https://localhost:3000/single_cell/study/SCP94/pairwise-test-1?cluster=UMAP&spatialGroups=--&annotation=UPDATEXML--group--study&subsample=all#study-visualize

 I see the expected `Bad request` message:
<img width="1292" alt="Screenshot 2024-11-13 at 4 11 36 PM" src="https://github.com/user-attachments/assets/15f57afd-a6d0-4b48-b721-0c0d14c924f8">

BUT if I use URL https://localhost:3000/single_cell/study/SCP94/pairwise-test-1?cluster=UMAP&spatialGroups=--&annotation=UPDATEXML&subsample=all#study-visualize
Notice that URL has bogus <annotation> instead of <annotation>--group--study 

Then I see the pre-PR result, a warning emitted by [ScatterPlot.jsx](https://github.com/broadinstitute/single_cell_portal_core/blob/59ad7bf7dbe6af7bd65570dd754a8fa283e81628/app/javascript/components/visualization/ScatterPlot.jsx#L607) : 
<img width="1183" alt="Screenshot 2024-11-13 at 4 10 47 PM" src="https://github.com/user-attachments/assets/7b84ed9d-9c83-45dd-88c0-57961277ebd1">
Since this reflects pre-PR behavior, I'm guessing this URL change bypasses the short circuit we want in place.

Because it seems much more likely that bogus URLs will replace the value for `annotation` wholesale (and not preserve the \<annotation\>--group--study syntax), I'm requesting a tweak to ensure a shortciruit occurs in the wholesale replacement of  `annotation` case.

2024-11-14 17:58 UTC, jlchang approved these changes
Thanks for making non-existent {name} requests shortcircuit, @bistline.

Everything looks good to me!

2024-11-14 18:10 UTC, bistline commented
Test failure is known wonkiness in `AbTest` distribution calculation

2024-11-14 18:13 UTC, merged