* SCP-2763 Send user metric ID to ingest pipeline
broadinstitute/single_cell_portal_core pull request #877
Opened 2021-01-26 13:15 UTC by knapii-developments

2021-01-26 20:13 UTC, eweitz approved these changes

2021-01-26 20:36 UTC, bistline requested changes
I think we might possibly have an issue with the `metrics_uuid` not getting assigned which is causing ingest runs not to initiate.  In normal usage, this would always get set when a user signs in.  However, since most of these tests simulate a login without actually performing one, we aren't setting it in tests, and the ingest runs are all erroring out before even launching.

I think we can handle by doing a couple of things:

1. auto-set the `metrics_uuid` field for all users in `db/seeds.rb`
2. in `test/factories/user.rb`, add the following code after line 13:
```
metrics_uuid {SecureRandom.uuid}
```

Without this value being present, I think the output of `PapiClient#get_command_line` is getting munged so that the value for `action` is passed as `metrics_uuid`, and this is causing a failure before the job can even launch.

2021-01-27 17:50 UTC, devonbush commented
good points Jon--agree with those changes.  One other thing we could do to mitigate this is to have these methods check if metrics_uuid is null, and if so, just use the dedicated constant ingest_pipeline mixpanel uuid that we are using.  that will make sure these methods never fail due to mixpanel user wonkiness

2021-01-27 17:51 UTC, devonbush requested changes
overall looks good, just the cleanups needed to make sure tests work

2021-01-29 18:38 UTC, devonbush approved these changes

2021-02-01 15:24 UTC, knapii-developments commented
> I think we might possibly have an issue with the `metrics_uuid` not getting assigned which is causing ingest runs not to initiate. In normal usage, this would always get set when a user signs in. However, since most of these tests simulate a login without actually performing one, we aren't setting it in tests, and the ingest runs are all erroring out before even launching.
> 
> I think we can handle by doing a couple of things:
> 
> 1. auto-set the `metrics_uuid` field for all users in `db/seeds.rb`
> 2. in `test/factories/user.rb`, add the following code after line 13:
> 
> ```
> metrics_uuid {SecureRandom.uuid}
> ```
> 
> Without this value being present, I think the output of `PapiClient#get_command_line` is getting munged so that the value for `action` is passed as `metrics_uuid`, and this is causing a failure before the job can even launch.

This has been handled in e19bbb0

2021-02-02 14:34 UTC, bistline approved these changes

2021-02-03 20:16 UTC, merged