adding some missing analytics events
broadinstitute/single_cell_portal_core pull request #925
Opened 2021-03-17 01:33 UTC by devonbush

This cleans up a couple places in the explore tab where we weren't tracking events well

To test:
1. open a study with the react_explore feature flag on
2. Open the chrome debugger with the network tab
3. type/select a gene in the search box
4. confirm an event gets posted to bard with name 'input:change' and text `study-gene-search:add`
5. Hit enter or click the search bar. 
6. confirm an event gets posted to bard with name 'click:button' and text 'gene-search-submit'
7. use the 'x' or backspace to remove a gene entry from the search bar
8. confirm an event gets posted to bard with name 'input:change' and text `study-gene-search:remove`

2021-03-17 13:49 UTC, bistline approved these changes

2021-03-18 13:50 UTC, eweitz requested changes
Great stuff!  With some refinement, I think this will be good to go.

2021-03-18 13:50 UTC, eweitz commented on app/javascript/components/explore/StudyGeneField.js
> +              log('input:change', { text: `study-gene-search:${actionName}` })
Blockers: 
* SCP naming pattern for interactions is `action:element`, not `element:action` (`change:menu`, `click:link`, etc.).  Maybe that's worth changing later, but for now let's go for internal consistency.
* The `text` value here is inconsistent with other uses of `text` in Mixpanel
* We should capture that A) this is a multiselect, and B) what value is being added or removed

Either suggestion below would satisfy those concerns.

Option A: Enable easier comparison, breakdowns, etc. across search types and contexts, like existing `search` event does:

```suggestion
              log('search-interaction', { 
                type: 'gene',
                scope: 'study', 
                action: `${actionName}:multiselect`
                text: value
              })
```

Option B: Enable easier comparison, breakdowns across all multiselect actions:

```suggestion
              log('$actionName:multiselect', { 
                widgetName: `study-gene-search`,
                action: actionName
                text: value
              })
```
```

2021-03-18 13:50 UTC, eweitz commented on app/javascript/packs/application.js
> +  $(document).on('change', 'select', logMenuChange)
Nice!

2021-03-18 14:10 UTC, devonbush commented
closing this PR, will address Eric's comment in the other GeneSearch PR

2021-03-18 14:10 UTC, closed without merging