Add informational tooltip for "Scaled mean expression" in dot plot (SCP-3193)
broadinstitute/single_cell_portal_core pull request #941
Opened 2021-03-24 17:12 UTC by eweitz

This adds a small tooltip beside the "Scaled mean expression" legend entry in dot plots.  At least two users have been confused by the label.  This tooltip adds the explanation we've given them, now placed in a context where it will more easily help other users.

Default icon:
<img width="1680" alt="Dot_plot_information_icon_SCP_2021-03-24" src="https://user-images.githubusercontent.com/1334561/112353266-f8662880-8ca1-11eb-822d-9f890bdd537b.png">

Active icon:
<img width="700" alt="Dot_plot_information_icon_active_SCP_2021-03-24" src="https://user-images.githubusercontent.com/1334561/112353388-13d13380-8ca2-11eb-9e03-0301452d5ede.png">

This satisfies SCP-3193.

2021-03-24 17:17 UTC, bistline approved these changes

2021-03-24 19:17 UTC, jlchang requested changes
I've used the word "across" (because "for" could imply for each individual gene expression value being scaled) but if we want to get more technical, we should verify that we're using the calculated mean and then replace "across" with "the calculated mean expression for"

2021-03-24 19:17 UTC, jlchang commented on app/javascript/components/visualization/DotPlotLegend.js
> +    Scaling is relative to the each gene's expression for all cells in each
```suggestion
    Scaling is relative to each gene's expression across all cells in a given
```

2021-03-24 19:22 UTC, jlchang approved these changes

2021-03-25 15:54 UTC, devonbush approved these changes
Nice, I appreciate the use of popover here instead of just data-toggle tooltip/title -- let you make the UI very elegant

2021-03-25 15:56 UTC, devonbush requested changes
Please add a data-analytics-name to the icon so that we can track clicks on it appropriately, otherwise looks good

2021-03-25 18:35 UTC, eweitz commented
The [failed build](https://travis-ci.com/github/broadinstitute/single_cell_portal_core/builds/221220685) is a false-positive, related to an issue with `mimemagic` that Jon noted at standup today.  `yarn test` passes locally.

2021-03-25 19:17 UTC, devonbush approved these changes

2021-03-25 20:37 UTC, merged