removing gene_study_filter feature flag (SCP-3228)
broadinstitute/single_cell_portal_core pull request #967
Opened 2021-04-05 20:11 UTC by devonbush

SCP-3228. This feature flag was added for prototype development last summer, and never ended up being expanded on.  Being deleted now as XDSS development will make it obsolete.

2021-04-05 20:14 UTC, bistline approved these changes

2021-04-06 13:13 UTC, eweitz requested changes
After a small fix, this looks good to go.

2021-04-06 13:13 UTC, eweitz commented on db/migrate/20210405192922_remove_gene_search_flag.rb
> +class RemoveSpatialFeatureFlag < Mongoid::Migration
```suggestion
class RemoveGeneStudyFilterFlag < Mongoid::Migration
```

Or another related name.

2021-04-07 17:17 UTC, eweitz approved these changes

2021-04-08 00:51 UTC, merged