removing 'url_safe_token' functionality (SCP-2955)
broadinstitute/single_cell_portal_core pull request #976
Opened 2021-04-12 21:09 UTC by devonbush

SCP-2955.  Now that we implemented 'cookie allowed API routes', url_safe_token is no longer needed.  url_safe _token was implemented to support passing an API url that morpheus could use, but since morpheus is always invoked on the SCP page itself, the cookie will be passed along, and we can authenticate with that.  

TO TEST:
 0. Sign in, go to a private study, do a multi-gene search
 1. confirm dotplot and heatmap load successfully.
 2. look in the console, and find the URL corresponding to the 'cell_values' request.  e.g. https://localhost:3000/single_cell/api/v1/studies/SCP4/annotations/biosample_id/cell_values?annotation_scope=study&annotation_type=group&cluster=X%20cluster
 3. sign out
 4. try to load that URL directly, confirm it fails

2021-04-13 14:24 UTC, bistline requested changes
Looks good, and I confirm it works.  The following code should also be removed:

- https://github.com/broadinstitute/single_cell_portal_core/blob/development/app/models/user.rb#L63
- https://github.com/broadinstitute/single_cell_portal_core/blob/development/app/controllers/users/omniauth_callbacks_controller.rb#L14

Also, the test `test/api/visualization/expression_controller_test.rb#'methods should check view permissions'` lacks a positive assertion (i.e. 200 response check).  The corresponding `annotations_controller_test.rb` does have this assertion, so we should do it on the expression side as well.

2021-04-13 14:43 UTC, devonbush commented
I like both those ideas.  I'll add the positive test.  the user.authentication_token code shows up in a lot of places, though, so I'll reserve that for a separate ticket and PR (also it may overlap with SCP-3134)

2021-04-13 15:38 UTC, eweitz approved these changes

2021-04-14 14:33 UTC, bistline approved these changes

2021-04-14 15:18 UTC, merged